# Lab 4 - Wybrane zagadnienia algebry liniowej, faktoryzacja

Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x Nastepnie rozwiąz rownanie Ax=b trzema metodami:
- inv()
- \
- factorize()

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie fukcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy od drugiego wywołania!

In [1]:
x = rand(1000)
A = rand(1000, 1000)
b = A * x

1000-element Array{Float64,1}:
 243.77889942926248
 242.4470818134254 
 235.54602167759052
 243.42501900996058
 241.06851845291717
 248.80344325080415
 240.2917292150318 
 236.64328803480478
 230.39381384411095
 249.47334617033005
 236.8335820100992 
 237.82337753971012
 238.54608561229563
   ⋮               
 235.01911085083174
 231.5645167745272 
 239.04373877035948
 240.4308110347587 
 236.129900129215  
 246.4605428991383 
 246.64010834244365
 243.59814324996287
 242.21587392188607
 235.55146312058594
 238.5084991008263 
 241.01739911883516

In [3]:
res = @time inv(A) * b

  0.073661 seconds (11 allocations: 8.134 MiB)


1000-element Array{Float64,1}:
 0.8709892458466868 
 0.8278849971475353 
 0.29091807708253015
 0.4487692631992104 
 0.7611236769914029 
 0.5947079136448252 
 0.26326199026847874
 0.9104351693551358 
 0.6209054392970117 
 0.9355314008288858 
 0.9455671884430501 
 0.9671863750630258 
 0.8797574277486184 
 ⋮                  
 0.9142691624482584 
 0.5865492676513107 
 0.43202716122850937
 0.9199608736359508 
 0.839883088868568  
 0.7472696000262857 
 0.29453595905459906
 0.7872851766670941 
 0.3000107566640793 
 0.6148433508699256 
 0.8059150825429002 
 0.3926520621786551 

In [5]:
res2 = @time A\b

  0.031490 seconds (9 allocations: 7.645 MiB)


1000-element Array{Float64,1}:
 0.8709892458470836 
 0.8278849971463424 
 0.2909180770813916 
 0.44876926319907195
 0.7611236769889637 
 0.5947079136455977 
 0.26326199026804914
 0.9104351693550808 
 0.6209054392952543 
 0.9355314008303098 
 0.9455671884428912 
 0.9671863750683526 
 0.8797574277480879 
 ⋮                  
 0.9142691624485972 
 0.5865492676517312 
 0.43202716122797014
 0.9199608736368678 
 0.8398830888693278 
 0.74726960002323   
 0.2945359590544866 
 0.7872851766673495 
 0.3000107566642583 
 0.6148433508738717 
 0.8059150825423508 
 0.3926520621796825 

In [7]:
using LinearAlgebra
res3 = @time factorize(A)\b

  0.026157 seconds (9 allocations: 7.645 MiB)


1000-element Array{Float64,1}:
 0.8709892458470836 
 0.8278849971463424 
 0.2909180770813916 
 0.44876926319907195
 0.7611236769889637 
 0.5947079136455977 
 0.26326199026804914
 0.9104351693550808 
 0.6209054392952543 
 0.9355314008303098 
 0.9455671884428912 
 0.9671863750683526 
 0.8797574277480879 
 ⋮                  
 0.9142691624485972 
 0.5865492676517312 
 0.43202716122797014
 0.9199608736368678 
 0.8398830888693278 
 0.74726960002323   
 0.2945359590544866 
 0.7872851766673495 
 0.3000107566642583 
 0.6148433508738717 
 0.8059150825423508 
 0.3926520621796825 

In [8]:
using DataFrames
l1 = sqrt(dot(x-res, x-res))
l2 = sqrt(dot(x-res2, x-res2))
l3 = sqrt(dot(x-res3, x-res3))
df1 = DataFrame()
df1[:Funkcja] = [1, 2, 3]
df1[:JakoscWyniku] = [l1, l2, l3]
show(df1)

3×2 DataFrame
│ Row │ Funkcja │ JakoscWyniku │
│     │ Int64   │ Float64      │
├─────┼─────────┼──────────────┤
│ 1   │ 1       │ 3.37644e-11  │
│ 2   │ 2       │ 2.49175e-11  │
│ 3   │ 3       │ 2.49175e-11  │

In [9]:
using Statistics, DataFrames,CSV, Plots
input="resultsLab3.csv"
mydata=CSV.read(input, delim=";")
dataGrouped2=by(mydata, [:size, :fun], timeMean = :time => mean, std = :time => std)

60×4 DataFrame
│ Row │ size  │ fun   │ timeMean │ std      │
│     │ Int64 │ Int64 │ Float64  │ Float64  │
├─────┼───────┼───────┼──────────┼──────────┤
│ 1   │ 50    │ 1     │ 9.2401   │ 7.545    │
│ 2   │ 100   │ 1     │ 34.7415  │ 13.5702  │
│ 3   │ 150   │ 1     │ 103.126  │ 14.3358  │
│ 4   │ 200   │ 1     │ 254.64   │ 22.5465  │
│ 5   │ 250   │ 1     │ 516.138  │ 26.3776  │
│ 6   │ 300   │ 1     │ 872.495  │ 76.2698  │
│ 7   │ 350   │ 1     │ 1431.21  │ 12.3553  │
│ 8   │ 400   │ 1     │ 2221.96  │ 20.5871  │
│ 9   │ 450   │ 1     │ 3218.72  │ 37.6982  │
│ 10  │ 500   │ 1     │ 4629.2   │ 285.59   │
⋮
│ 50  │ 500   │ 3     │ 1.2513   │ 0.255873 │
│ 51  │ 550   │ 3     │ 1.5703   │ 0.320989 │
│ 52  │ 600   │ 3     │ 1.9117   │ 0.27676  │
│ 53  │ 650   │ 3     │ 2.1196   │ 0.446872 │
│ 54  │ 700   │ 3     │ 2.33     │ 0.313876 │
│ 55  │ 750   │ 3     │ 2.4488   │ 0.178183 │
│ 56  │ 800   │ 3     │ 2.9574   │ 0.290639 │
│ 57  │ 850   │ 3     │ 3.251    │ 0.189989 │
│ 58  │ 900   │ 3     │ 3.8962   │ 0.255706 │
│ 59  │ 950   │ 3     │ 5.1142   │ 1.77269  │
│ 60  │ 1000  │ 3     │ 4.7183   │ 0.208089 │

Policz wspołczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda zaprezentowana na tym laboratorium). Porównaj wyniki z tymi otrzymanymi poprzednio.

In [10]:
using Polynomials
fit_n2=polyfit(dataGrouped2[1:20, :].size ,dataGrouped2[1:20, :].timeMean,3)

Poly(-686.3418169865392 + 10.55886288657094*x - 0.03947908472233775*x^2 + 7.64261725375981e-5*x^3)

In [11]:
B = zeros(20, 4)
x = dataGrouped2[1:20, :].size
y = dataGrouped2[1:20, :].timeMean

B[:,1]=x.^3
B[:,2]=x.^2
B[:,3]=x
B[:,4]=ones(20)
B\y

4-element Array{Float64,1}:
    7.64261725375981e-5
   -0.03947908472233775
   10.55886288657094   
 -686.3418169865392    

Znajdź i zaprezentuj działanie innego zastosowania wybranej faktoryzacji.

Wybrany temat:
tworzenie pseudoinwersji macierzy(http://buzzard.ups.edu/courses/2014spring/420projects/math420-UPS-spring-2014-macausland-pseudo-inverse-present.pdf).

In [11]:
using LinearAlgebra
C = zeros(4,3)
C[:,1]=[1,1,1,1]
C[:,2]=[-1,4,4,-1]
C[:,3]=[4,-2,2,0]
CF=factorize(C)
R1 = zeros(3,4)
R1[:,1:3] = inv(CF.R)
Q1 = transpose(CF.Q)
C1 = R1*Q1
Res=zeros(3,4)
Res[1,:] = C1[3,:]
Res[2,:] = C1[1,:]
Res[3,:] = C1[2,:]
println(C)
println(C*Res*C)
println(Res)
println(Res*C*Res)
println(Res*C)
println(Hermitian(transpose(Res*C)))
println(C*Res)
println(Hermitian(transpose(C*Res)))

[1.0 -1.0 4.0; 1.0 4.0 -2.0; 1.0 4.0 2.0; 1.0 -1.0 0.0]
[0.9999999999999998 -1.0000000000000018 3.9999999999999996; 1.0 4.0 -2.0; 1.0 3.9999999999999996 1.9999999999999998; 1.0 -1.0000000000000009 -2.220446049250313e-16]
[0.19999999999999993 0.29999999999999993 -0.10000000000000005 0.6000000000000002; -0.04999999999999999 0.05000000000000003 0.15000000000000002 -0.15000000000000005; 0.12500000000000003 -0.125 0.12499999999999994 -0.125]
[0.19999999999999993 0.29999999999999993 -0.10000000000000016 0.6000000000000003; -0.049999999999999996 0.05000000000000005 0.15000000000000005 -0.15000000000000008; 0.12500000000000003 -0.12500000000000003 0.12499999999999992 -0.12499999999999999]
[1.0 -5.551115123125783e-16 -2.498001805406602e-16; 2.7755575615628914e-17 1.0000000000000002 0.0; -2.7755575615628914e-17 -2.220446049250313e-16 1.0]
[1.0 2.7755575615628914e-17 -2.7755575615628914e-17; 2.7755575615628914e-17 1.0000000000000002 -2.220446049250313e-16; -2.7755575615628914e-17 -2.2204460492503